[project]
name = "clark"
version = "0.8.1"
description = "Pixi environment for quantitative social science course and book manuscript."
authors = ["John McLevey <mclevey@mun.ca>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = ">=3.11,<3.13"
pip = ">=25.2,<26"
ipykernel = ">=6.30.1,<7"
jupyter = ">=1.1.1,<2"
pymc = ">=5.25.1,<6"
bambi = ">=0.15.0,<0.16"
arviz = ">=0.22.0,<0.23"
graph-tool = { version = ">=2.97,<3", channel = "conda-forge" }
pandas = { version = ">=2.3.1,<3", channel = "conda-forge" }
numpy = { version = ">=2.3.2,<3", channel = "conda-forge" }
matplotlib = { version = ">=3.10.5,<4", channel = "conda-forge" }
pyyaml = { version = ">=6.0.2,<7", channel = "conda-forge" }
graphviz = { version = ">=11,<13", channel = "conda-forge" }
python-graphviz = { version = ">=0.20,<1", channel = "conda-forge" }
statsmodels = ">=0.14.5,<0.15"

[pypi-dependencies]
clark-qss = { path = "./clark", editable = true }
